#!/bin/bash
set -euo pipefail
set -vx

uvx github-backup cloudcity --organization --output-directory /Users/Shared/GitHub/cloudcity \
  --keychain-account cloudcity --keychain-name github-backup-cloudcity \
  --incremental --all --repositories --fork --private

uvx github-backup rubytogether --organization --output-directory /Users/Shared/GitHub/rubytogether \
  --keychain-account rubytogether --keychain-name github-backup-rubytogether \
  --incremental --all --repositories --fork --private

uvx github-backup bubblesortio --organization --output-directory /Users/Shared/GitHub/bubblesortio \
  --keychain-account bubblesortio --keychain-name github-backup-bubblesortio \
  --incremental --all --repositories --fork --private
