#!/bin/bash
set -euo pipefail
set -vx

uvx github-backup indirect --output-directory /Users/Shared/GitHub/indirect \
  --keychain-account indirect --keychain-name github-backup-indirect \
  --incremental --all --gists --repositories --fork --private

uvx github-backup spinel-coop --organization --output-directory /Users/Shared/GitHub/spinel-coop \
  --keychain-account spinel-coop --keychain-name github-backup-spinel-coop \
  --incremental --all --repositories --fork --private

uvx github-backup sunchaserio --organization --output-directory /Users/Shared/GitHub/sunchaserio \
  --keychain-account sunchaserio --keychain-name github-backup-sunchaserio \
  --incremental --all --repositories --fork --private

uvx github-backup obliviousnetwork --organization --output-directory /Users/Shared/GitHub/obliviousnetwork \
  --keychain-account obliviousnetwork --keychain-name github-backup-obliviousnetwork \
  --incremental --all --repositories --fork --private

uvx github-backup filecabin --organization --output-directory /Users/Shared/GitHub/filecabin \
  --keychain-account filecabin --keychain-name github-backup-filecabin \
  --incremental --all --repositories --fork --private
