#!/bin/bash

[[ -e "$HOME/.zsh/homebrew.zsh" ]] && . "$HOME/.zsh/homebrew.zsh"

if [[ -e "/opt/homebrew/bin/mosh" ]]; then
  MOSH="/opt/homebrew/bin/mosh"
else
  MOSH="/usr/local/bin/mosh"
fi
SERVER="--server=/usr/local/bin/mosh-server"

case "$1" in
home)
  "$MOSH" "$SERVER" --ssh="ssh -p 2222" home.arko.me ~/.bin/tmux-named main
  ;;
*)
  "$MOSH" "$SERVER" "$@"
  ;;
esac
