#!/bin/bash

# Pull all the submodules
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
(
  cd $DIR/..
  git submodule update --init
)

# Configure ShiftIt to add 1/3 and 2/3 after 1/2 on repeated invocations
defaults write org.shiftitapp.ShiftIt multipleActionsCycleWindowSizes YES

# Install Heroku run:local plugin
if [[ ! "$(heroku plugins)" == *"heroku-run-localjs"* ]]; then
  heroku plugins:install heroku-run-localjs
fi

# Open the Backblaze installer and get it set up, too
if [[ ! -d /Library/PreferencePanes/BackblazeBackup.prefPane ]]; then
  open -a "/usr/local/Caskroom/backblaze/latest/Backblaze Installer.app"
fi

# Install rustup, cargo, and rust nightly
if [[ ! -d ~/.cargo ]]; then
  curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --default-toolchain nightly
fi

echo "configuration complete"
