#!/bin/bash

# Pull all the submodules
ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"

(
  cd $ROOT
  git submodule update --init
)

# Configure ShiftIt to add 1/3 and 2/3 after 1/2 on repeated invocations
defaults write org.shiftitapp.ShiftIt multipleActionsCycleWindowSizes YES

# Install Heroku run:local plugin
if [[ ! "$(heroku plugins)" == *"heroku-run-localjs"* ]]; then
  heroku plugins:install heroku-run-localjs
fi

# Open the Backblaze installer
if [[ ! -d /Library/PreferencePanes/BackblazeBackup.prefPane ]]; then
  open -a "/usr/local/Caskroom/backblaze/latest/Backblaze Installer.app"
fi

# Open the Little Snitch installer
if [[ -e $(ls /usr/local/Caskroom/little-snitch/*/*.dmg) ]]; then
  hdiutil attach /usr/local/Caskroom/little-snitch/*/*.dmg
  open /Volumes/Little\ Snitch*/Little\ Snitch\ Installer.app
fi

# Install rustup, cargo, and rust nightly
if [[ ! -d ~/.cargo ]]; then
  curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --default-toolchain nightly
fi

# Copy youtube-dl to local bin so it can self-update
if [[ -f /usr/local/bin/youtube-dl ]]; then
  cp /usr/local/bin/youtube-dl ~/.bin/
fi

# Install Menlo for Powerline, etc
cp support/fonts/* ~/Library/Fonts/

# Install Terminal theme
THEME=$(cat "$ROOT/support/terminal/Solarized Dark Menlo.terminal")
plutil -replace "Window Settings.Solarized Dark" -xml "$THEME" \
  ~/Library/Preferences/com.apple.Terminal.plist
defaults write com.apple.Terminal "Default Window Settings" -string "Solarized Dark"
defaults write com.apple.Terminal "Startup Window Settings" -string "Solarized Dark"

echo "configuration complete, restart your Terminal"
osascript -e 'tell application "Terminal" to quit'
