#!/bin/bash
set -euo pipefail
set -vx
echo "moving dotfiles for chezmoi..."

# relocate the checkout to the usual ~/src/indirect/dotfiles location
[[ -d ~/src/indirect ]] || mkdir -p ~/src/indirect
[[ -d ~/src/indirect/dotfiles ]] || mv ~/.dotfiles ~/src/indirect/dotfiles

# link the conventional .dotfiles location
[[ -L ~/.dotfiles ]] || ln -sf ~/src/indirect/dotfiles ~/.dotfiles

# link the chezmoi ~/.local/share/chezmoi location
[[ -d ~/.local/share ]] || mkdir -p ~/.local/share
[[ -L ~/.local/share/chezmoi ]] || ln -sf ~/src/indirect/dotfiles ~/.local/share/chezmoi

echo "setting up Brewfile"
brew install chezmoi
chezmoi apply ~/.Brewfile
