#!/bin/bash


export BREW_PREFIX=$(brew --prefix)

# Pull all the submodules
ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"

(
  cd $ROOT
  git submodule update --init
)

# Configure ShiftIt to add 1/3 and 2/3 after 1/2 on repeated invocations
defaults write org.shiftitapp.ShiftIt multipleActionsCycleWindowSizes YES

# Install Heroku run:local plugin
if [[ ! "$(heroku plugins)" == *"heroku-run-localjs"* ]]; then
  heroku plugins:install heroku-run-localjs
fi

# Open the Backblaze installer
if [[ ! -d /Library/PreferencePanes/BackblazeBackup.prefPane ]]; then
  open -a "$BREW_PREFIX/Caskroom/backblaze/*/*.app"
fi

# Install rustup, cargo, and rust nightly
if [[ ! -d ~/.cargo ]]; then
  curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --default-toolchain nightly
fi

# Install the current default Ruby version
eval $(grep DEFAULT_RUBY_VERSION= zshrc)
if [[ ! -d "$HOME/.rubies/ruby-$DEFAULT_RUBY_VERSION" ]]; then
  chruby install "$DEFAULT_RUBY_VERSION"
  chruby reload
fi

# Copy youtube-dl to local bin so it can self-update
if [[ -f "$BREW_PREFIX/bin/youtube-dl" ]]; then
  cp "$BREW_PREFIX/bin/youtube-dl" ~/.bin/
fi

# remap capslock to control
$ROOT/support/remap-capslock-to-control.sh

# add dvorak to keyboard layouts
defaults import com.apple.HIToolbox $ROOT/support/defaults/com.apple.HIToolbox.plist

# Set up bottom-left corner to sleep display
defaults write com.apple.dock wvous-bl-corner -int 10
defaults write com.apple.dock wvous-bl-modifier -int 0

# turn on night shift
nightlight schedule start

# set up puma-dev
echo "About to set up puma-dev, you'll need to enter your password"
sudo puma-dev -setup
puma-dev -install

# Set up git signing
echo "You need to use Keychain Access to copy the 'bpb key' keychain entry from iCloud to your login keychain."
echo "When you're done, come back and push enter."
read
bpb print | gpg --import
echo $(gpg --list-keys --fingerprint | grep "andre@arko.net" -B 1 | head -1 | tr -d '[:space:]'):6: | gpg --import-ownertrust

# Install licensed Onivim2
echo "You need to use Keychain Access to copy the 'onivim2' keychain entry from iCloud to your login keychain. When you're done, come back and push enter."
read
export HOMEBREW_ONIVIM_SERIAL="$(security find-generic-password -s onivim2 -w)"
brew install marblenix/onivim2/onivim2

# Open the stuff that needs to be configured
open -a "Alfred 4"
open -a "Bartender 4"
open -a "Dropbox"
open -a "Due"
open -a "Hammerspoon"
open -a "Hookshot"
open -a "Karabiner-Elements"
open -a "Keyboard Maestro"
open -a "Little Snitch"
open -a "MenuMeters"
open -a "SoundSource"

# Install Terminal theme
THEME=$(cat "$ROOT/support/terminal/Solarized Dark Menlo NF.terminal")
plutil -replace "Window Settings.Solarized Dark" -xml "$THEME" \
  ~/Library/Preferences/com.apple.Terminal.plist
defaults write com.apple.Terminal "Default Window Settings" -string "Solarized Dark"
defaults write com.apple.Terminal "Startup Window Settings" -string "Solarized Dark"

echo "configuration complete, restart your Terminal"
osascript -e 'tell application "Terminal" to quit'
