"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[aliases]
tug = ["util", "exec", "--", "sh", "-c", """
if [ "x$1" = "x" ]; then
  jj bookmark move --from "closest_bookmark(@)" --to "closest_pushable(@)"
else
  jj bookmark move --to "closest_pushable(@)" "$@"
fi
""", ""]

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_remote_bookmark(to)' = 'heads(::to & remote_bookmarks())'
'closest_pushable(to)' = 'heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()))'

[git]
push-new-bookmarks = true

[[--scope]]
--when.commands = ["diff", "show"]

[--scope.ui]
# https://github.com/jj-vcs/jj/blob/v0.25.0/docs/config.md#processing-contents-to-be-paged
pager = "delta"
# NOTE: this is required when using `delta` as a pager
diff.format = "git"

[user]
name = "André Arko"
email = "andre@arko.net"

[ui]
editor = "mvim -f"
